name: Exchanging artifacts between workflows
description: TBD
author: Elana Zobin
branding:
  icon: 'box'
  color: 'purple'
inputs:
  github-token:
    description: >-
      GitHub Personal Access Token with the 'repo' scope assigned.
    required: true
  artifact-name:
    description: >-
    required: true
  path:
    description: >-
    required: false
    default: "./"
outputs:
  artifact-status:
    description: >-
      return status of the artifact:
          available: if artifact is available for download
          not-found: if artifact is not found
runs:
  using: node16
  main: ./dist/index.js